#pragma once

// Stats: {"leaves":56,"nodes":111,"maxDepth":7,"minDepth":5,"avgPath":5.89286,"sortedPath":6,"reversePath":5,"fullness":43.75}

#include "dtsort_common.hh"
#include "dtsort3_full.hh"
#include "dtsort5_full.hh"

// Generated by dtsort-codegen
#define N(label, row, col, labelTrue, labelFalse) label: if (compare(row, col)) goto labelTrue; else goto labelFalse;
#define R DT_RETURN
#define R_SORTED DT_RETURN_SORTED

template<typename RandomAccessIterator, typename Compare>
DT_ALWAYS_INLINE
inline DT_RETURN_TYPE dtsort8gs53(const RandomAccessIterator& first, [[maybe_unused]] const RandomAccessIterator& last, const Compare& compare) {
assert(last-first==8);
auto &a = *(first+0);
auto &b = *(first+1);
auto &c = *(first+2);
auto &d = *(first+3);
auto &e = *(first+4);
auto &f = *(first+5);
auto &g = *(first+6);
auto &h = *(first+7);

#if DT_ADAPTIVE
bool s1 = dtsort5(first, first+5, compare);
bool s2 = dtsort3(first+5, first+8, compare);
if (DT_UNLIKELY(s1 && s2 && !compare(*(first+5), *(first+4)))) return true;
#else
dtsort5(first, first+5, compare);
dtsort3(first+5, first+8, compare);
#endif

N(n1717802a,g,c,n17169981,n1715b2d8)
N(n17169981,f,a,nf6413be,n7b18dfb)
N(nf6413be,g,a,nf5bf7cd,nf53dbdc)
N(nf5bf7cd,h,c,nf5bf77c,nf5bf72b)
N(nf5bf77c,h,a,lf5bf4a3,nf5bf1ca)
N(nf5bf1ca,h,b,lf5bf0d7,lf5befe4)
N(nf5bf72b,h,d,lf5bf710,nf5bf6f5)
N(nf5bf6f5,h,e,lf5bf6ec,lf5bf6e3)
N(nf53dbdc,g,b,nf5127e1,nf4e73e6)
N(nf5127e1,h,c,nf512790,nf51273f)
N(nf512790,h,b,lf51269d,lf5125aa)
N(nf51273f,h,d,lf512724,nf512709)
N(nf512709,h,e,lf512700,lf5126f7)
N(nf4e73e6,h,d,nf4e73cb,nf4e73b0)
N(nf4e73cb,h,c,lf4e737a,lf4e7329)
N(nf4e73b0,h,e,lf4e73a7,lf4e739e)
N(n7b18dfb,h,d,n7b18de0,n7b18dc5)
N(n7b18de0,g,b,n7aed9e5,n7ac25ea)
N(n7aed9e5,h,b,l7aed8f2,n7aed7ff)
N(n7aed7ff,h,c,l7aed7ae,l7aed75d)
N(n7ac25ea,f,b,n51b4ea9,n28a7768)
N(n51b4ea9,h,c,l51b4e58,l51b4e07)
N(n28a7768,h,c,l28a7717,l28a76c6)
N(n7b18dc5,h,e,n7b18dbc,n7b18db3)
N(n7b18dbc,f,b,n520b67b,l28fdf3a)
N(n520b67b,g,b,l51e0280,l51b4e85)
N(n7b18db3,f,b,n520b672,l28fdf31)
N(n520b672,g,b,l51e0277,l51b4e7c)
N(n1715b2d8,h,e,n1715b2cf,n1715b2c6)
N(n1715b2cf,f,b,n1484db8e,n11f4044d)
N(n1484db8e,f,a,ncd255cb,n51fd008)
N(ncd255cb,g,d,ncd208e8,lcd1bc05)
N(ncd208e8,h,d,lcd208cd,lcd208b2)
N(n51fd008,g,d,n51f8325,l51f3642)
N(n51f8325,h,d,l51f830a,l51f82ef)
N(n11f4044d,f,c,n111911e2,n103e1f77)
N(n111911e2,g,d,n1118c4ff,l1118781c)
N(n1118c4ff,h,d,l1118c4e4,l1118c4c9)
N(n103e1f77,g,d,n103dd294,n103d85b1)
N(n103dd294,h,d,l103dd279,l103dd25e)
N(n103d85b1,f,d,lff48a38,lfab8ebf)
N(n1715b2c6,f,b,n1484db85,n11f40444)
N(n1484db85,f,a,ncd255c2,n51fcfff)
N(ncd255c2,g,d,lcd208df,ncd1bbfc)
N(ncd1bbfc,g,e,lcd1a25b,lcd188ba)
N(n51fcfff,g,d,l51f831c,n51f3639)
N(n51f3639,g,e,l51f1c98,l51f02f7)
N(n11f40444,g,e,n11f3eaa3,n11f3d102)
N(n11f3eaa3,f,c,n1118f838,n103e05cd)
N(n1118f838,g,d,l1118ab55,l11185e72)
N(n103e05cd,f,d,nff50a54,lfac0edb)
N(nff50a54,g,d,lff4bd71,lff4708e)
N(n11f3d102,f,d,n11aad589,n1161da10)
N(n11aad589,f,c,l10cfe31e,lff4f0b3)
N(n1161da10,f,e,l1149863d,l1131326a)

lf5bf4a3:X(a,d,g,b,e,h,c,f);R
lf5bf0d7:X(a,c,f);X(b,e,h,d,g);R
lf5befe4:X(a,c,f);X(b,d,g);X(e,h);R
lf5bf710:X(a,c,e,h,f);X(b,d,g);R
lf5bf6ec:X(a,c,e,h,g,b,d,f);R
lf5bf6e3:X(a,c,e,g,b,d,f);R
lf51269d:X(a,b,e,h,d,g,c,f);R
lf5125aa:X(a,b,d,g,c,f);X(e,h);R
lf512724:X(a,b,d,g,c,e,h,f);R
lf512700:X(a,b,d,f);X(c,e,h,g);R
lf5126f7:X(a,b,d,f);X(c,e,g);R
lf4e737a:X(a,b,c,f);X(d,g);X(e,h);R
lf4e7329:X(a,b,c,e,h,f);X(d,g);R
lf4e73a7:X(a,b,c,e,h,g,d,f);R
lf4e739e:X(a,b,c,e,g,d,f);R
l7aed8f2:X(b,e,h,d,g,c,f);R
l7aed7ae:X(b,d,g,c,f);X(e,h);R
l7aed75d:X(b,d,g,c,e,h,f);R
l51b4e58:X(b,c,f);X(d,g);X(e,h);R
l51b4e07:X(b,c,e,h,f);X(d,g);R
l28a7717:X(c,f);X(d,g);X(e,h);R
l28a76c6:X(c,e,h,f);X(d,g);R
l51e0280:X(b,d,f);X(c,e,h,g);R
l51b4e85:X(b,c,e,h,g,d,f);R
l28fdf3a:X(c,e,h,g,d,f);R
l51e0277:X(b,d,f);X(c,e,g);R
l51b4e7c:X(b,c,e,g,d,f);R
l28fdf31:X(c,e,g,d,f);R
lcd208cd:X(a,b,c,d,g,e,h,f);R
lcd208b2:X(a,b,c,d,f);X(e,h,g);R
lcd1bc05:X(a,b,c,d,e,h,g,f);R
l51f830a:X(b,c,d,g,e,h,f);R
l51f82ef:X(b,c,d,f);X(e,h,g);R
l51f3642:X(b,c,d,e,h,g,f);R
l1118c4e4:X(c,d,g,e,h,f);R
l1118c4c9:X(c,d,f);X(e,h,g);R
l1118781c:X(c,d,e,h,g,f);R
l103dd279:X(d,g,e,h,f);R
l103dd25e:X(d,f);X(e,h,g);R
lff48a38:X(d,e,h,g,f);R
lfab8ebf:X(e,h,g,f);R
lcd208df:X(a,b,c,d,f);X(e,g);R
lcd1a25b:X(a,b,c,d,e,g,f);R
lcd188ba:X(a,b,c,d,e,f);R
l51f831c:X(b,c,d,f);X(e,g);R
l51f1c98:X(b,c,d,e,g,f);R
l51f02f7:X(b,c,d,e,f);R
l1118ab55:X(c,d,f);X(e,g);R
l11185e72:X(c,d,e,g,f);R
lff4bd71:X(d,f);X(e,g);R
lff4708e:X(d,e,g,f);R
lfac0edb:X(e,g,f);R
l10cfe31e:X(c,d,e,f);R
lff4f0b3:X(d,e,f);R
l1149863d:X(e,f);R
l1131326a:R_SORTED
}
#undef N
#undef R
#undef R_SORTED
