#pragma once
// Decision Tree Statistics:
//   Leaves: 126
//   Nodes:  251
//   Max depth: 8
//   Min depth: 6
//   Average path length: 7.07937
//   Path length (sorted input): 7
//   Path length (reverse input): 6
//   Tree fullness: 49.2188% (126 / 2^8)

#include "cycle.hh"
#include "dtsort4_full.hh"
#include "dtsort5_full.hh"

// Generated by dtsort-codegen
#ifndef DT_ADAPTIVE
#define DT_ADAPTIVE 1
#endif
#ifndef DT_UNLIKELY
#if defined(__GNUC__) || defined(__clang__)
#define DT_UNLIKELY(x) __builtin_expect(!!(x), 0)
#else
#define DT_UNLIKELY(x) (x)
#endif
#endif
#define N(label, row, col, labelTrue, labelFalse) label: if (compare(row, col)) goto labelTrue; else goto labelFalse;
#if DT_ADAPTIVE
#define R return false;
#define R_SORTED return true;
#else
#define R return;
#define R_SORTED return;
#endif

template<typename RandomAccessIterator, typename Compare>
#if defined(__GNUC__) || defined(__clang__)
__attribute__((always_inline))
#endif
#if DT_ADAPTIVE
// Returns true if the input was already sorted and no swaps were performed.
inline bool dtsort9gs54(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
#else
inline void dtsort9gs54(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
#endif
assert(last-first==9);
auto &a = *(first+0);
auto &b = *(first+1);
auto &c = *(first+2);
auto &d = *(first+3);
auto &e = *(first+4);
auto &f = *(first+5);
auto &g = *(first+6);
auto &h = *(first+7);
auto &i = *(first+8);

#if DT_ADAPTIVE
    bool s1 = dtsort5(first, first+5, compare);
    bool s2 = dtsort4(first+5, first+9, compare);
    if (DT_UNLIKELY(s1 && s2 && !compare(*(first+5), *(first+4)))) return true;
#else
dtsort5(first, first+5, compare);
dtsort4(first+5, first+9, compare);
#endif

N(n24fd14bcdf0, f, a, n18a8af5a34d, nc5449f78aa)
N(n18a8af5a34d, h, c, n18a8aed875c, n18a8ae56b6b)
N(n18a8aed875c, g, a, n189bb196bcb, n188eb45503a)
N(n189bb196bcb, h, a, n189bad07052, n189ba8774d9)
N(n189bad07052, i, c, n189bad06f5f, n189bad06e6c)
N(n189bad06f5f, i, a, l189bad066d4, n189bad05e49)
N(n189bad05e49, i, b, l189bad05b70, l189bad05897)
N(n189bad06e6c, i, d, l189bad06e1b, n189bad06dca)
N(n189bad06dca, i, e, l189bad06daf, l189bad06d94)
N(n189ba8774d9, h, b, n189ba6f2106, n189ba56cd33)
N(n189ba6f2106, i, c, n189ba6f2013, n189ba6f1f20)
N(n189ba6f2013, i, b, l189ba6f1d3a, l189ba6f1a61)
N(n189ba6f1f20, i, d, l189ba6f1ecf, n189ba6f1e7e)
N(n189ba6f1e7e, i, e, l189ba6f1e63, l189ba6f1e48)
N(n189ba56cd33, i, d, n189ba56cce2, n189ba56cc91)
N(n189ba56cce2, i, c, l189ba56cbef, l189ba56cafc)
N(n189ba56cc91, i, e, l189ba56cc76, l189ba56cc5b)
N(n188eb45503a, i, d, n188eb454fe9, n188eb454f98)
N(n188eb454fe9, h, b, n188eb2cfc16, n188eb14a843)
N(n188eb2cfc16, i, b, l188eb2cf93d, n188eb2cf664)
N(n188eb2cf664, i, c, l188eb2cf571, l188eb2cf47e)
N(n188eb14a843, g, b, n188a5cdf468, n1886087408d)
N(n188a5cdf468, i, c, l188a5cdf375, l188a5cdf282)
N(n1886087408d, i, c, l18860873f9a, l18860873ea7)
N(n188eb454f98, i, e, n188eb454f7d, n188eb454f62)
N(n188eb454f7d, g, b, n188a5fe9ba2, l18860b7e7c7)
N(n188a5fe9ba2, h, b, l188a5e647cf, l188a5cdf3fc)
N(n188eb454f62, g, b, n188a5fe9b87, l18860b7e7ac)
N(n188a5fe9b87, h, b, l188a5e647b4, l188a5cdf3e1)
N(n18a8ae56b6b, i, e, n18a8ae56b50, n18a8ae56b35)
N(n18a8ae56b50, g, b, n18a459eb775, n18a0058039a)
N(n18a459eb775, g, a, n18975ca9be4, n188a5f68053)
N(n18975ca9be4, h, d, n18975c7e7e9, l18975c533ee)
N(n18975c7e7e9, i, d, l18975c7e798, l18975c7e747)
N(n188a5f68053, h, d, n188a5f3cc58, l188a5f1185d)
N(n188a5f3cc58, i, d, l188a5f3cc07, l188a5f3cbb6)
N(n18a0058039a, g, c, n189e9407251, n189d228e108)
N(n189e9407251, h, d, n189e93dbe56, l189e93b0a5b)
N(n189e93dbe56, i, d, l189e93dbe05, l189e93dbdb4)
N(n189d228e108, h, d, n189d2262d0d, n189d2237912)
N(n189d2262d0d, i, d, l189d2262cbc, l189d2262c6b)
N(n189d2237912, g, d, l189ca70f34f, l189c2be6d8c)
N(n18a8ae56b35, g, b, n18a459eb75a, n18a0058037f)
N(n18a459eb75a, g, a, n18975ca9bc9, n188a5f68038)
N(n18975ca9bc9, h, d, l18975c7e7ce, n18975c533d3)
N(n18975c533d3, h, e, l18975c44d2a, l18975c36681)
N(n188a5f68038, h, d, l188a5f3cc3d, n188a5f11842)
N(n188a5f11842, h, e, l188a5f03199, l188a5ef4af0)
N(n18a0058037f, h, e, n18a00571cd6, n18a0056362d)
N(n18a00571cd6, g, c, n189e93f8b8d, n189d227fa44)
N(n189e93f8b8d, h, d, l189e93cd792, l189e93a2397)
N(n189d227fa44, g, d, n189ca757481, l189c2c2eebe)
N(n189ca757481, h, d, l189ca72c086, l189ca700c8b)
N(n18a0056362d, g, d, n189f8a3b06a, n189f0f12aa7)
N(n189f8a3b06a, g, c, l189e18c1f21, l189ca748dd8)
N(n189f0f12aa7, g, e, l189ee605366, l189ebcf7c25)
N(nc5449f78aa, f, b, n838282bfc9, n41c06606e8)
N(n838282bfc9, g, b, n833d3c0bee, n82f7f55813)
N(n833d3c0bee, h, c, n833d33effd, n833d2bd40c)
N(n833d33effd, h, b, n833d1b9c2a, n833d034857)
N(n833d1b9c2a, i, c, n833d1b9b37, n833d1b9a44)
N(n833d1b9b37, i, b, l833d1b985e, l833d1b9585)
N(n833d1b9a44, i, d, l833d1b99f3, n833d1b99a2)
N(n833d1b99a2, i, e, l833d1b9987, l833d1b996c)
N(n833d034857, i, d, n833d034806, n833d0347b5)
N(n833d034806, i, c, l833d034713, l833d034620)
N(n833d0347b5, i, e, l833d03479a, l833d03477f)
N(n833d2bd40c, h, d, n833d292011, n833d266c16)
N(n833d292011, i, d, l833d291fc0, n833d291f6f)
N(n833d291f6f, i, e, l833d291f54, l833d291f39)
N(n833d266c16, h, e, n833d25856d, l833d249ec4)
N(n833d25856d, i, e, l833d258552, l833d258537)
N(n82f7f55813, g, c, n82e0ddc6ca, n82c9c63581)
N(n82e0ddc6ca, h, c, n82e0d5aad9, n82e0cd8ee8)
N(n82e0d5aad9, i, d, n82e0d5aa88, n82e0d5aa37)
N(n82e0d5aa88, i, c, l82e0d5a995, l82e0d5a8a2)
N(n82e0d5aa37, i, e, l82e0d5aa1c, l82e0d5aa01)
N(n82e0cd8ee8, h, d, n82e0cadaed, n82e0c826f2)
N(n82e0cadaed, i, d, l82e0cada9c, n82e0cada4b)
N(n82e0cada4b, i, e, l82e0cada30, l82e0cada15)
N(n82e0c826f2, h, e, n82e0c74049, l82e0c659a0)
N(n82e0c74049, i, e, l82e0c7402e, l82e0c74013)
N(n82c9c63581, g, d, n82c213afbe, n82ba6129fb)
N(n82c213afbe, h, d, n82c210fbc3, n82c20e47c8)
N(n82c210fbc3, i, d, l82c210fb72, n82c210fb21)
N(n82c210fb21, i, e, l82c210fb06, l82c210faeb)
N(n82c20e47c8, h, e, n82c20d611f, l82c20c7a76)
N(n82c20d611f, i, e, l82c20d6104, l82c20d60e9)
N(n82ba6129fb, h, e, n82ba604352, n82ba5f5ca9)
N(n82ba604352, i, e, l82ba604337, l82ba60431c)
N(n82ba5f5ca9, g, e, l82b7ce8568, l82b53dae27)
N(n41c06606e8, f, c, n2bd5071e9d, n15e9a83652)
N(n2bd5071e9d, g, c, n2bbdef8d54, n2ba6d7fc0b)
N(n2bbdef8d54, h, c, n2bbde77163, n2bbddf5572)
N(n2bbde77163, i, d, n2bbde77112, n2bbde770c1)
N(n2bbde77112, i, c, l2bbde7701f, l2bbde76f2c)
N(n2bbde770c1, i, e, l2bbde770a6, l2bbde7708b)
N(n2bbddf5572, h, d, n2bbddca177, n2bbdd9ed7c)
N(n2bbddca177, i, d, l2bbddca126, n2bbddca0d5)
N(n2bbddca0d5, i, e, l2bbddca0ba, l2bbddca09f)
N(n2bbdd9ed7c, h, e, n2bbdd906d3, l2bbdd8202a)
N(n2bbdd906d3, i, e, l2bbdd906b8, l2bbdd9069d)
N(n2ba6d7fc0b, g, d, n2b9f257648, n2b9772f085)
N(n2b9f257648, h, d, n2b9f22c24d, n2b9f200e52)
N(n2b9f22c24d, i, d, l2b9f22c1fc, n2b9f22c1ab)
N(n2b9f22c1ab, i, e, l2b9f22c190, l2b9f22c175)
N(n2b9f200e52, h, e, n2b9f1f27a9, l2b9f1e4100)
N(n2b9f1f27a9, i, e, l2b9f1f278e, l2b9f1f2773)
N(n2b9772f085, h, e, n2b977209dc, n2b97712333)
N(n2b977209dc, i, e, l2b977209c1, l2b977209a6)
N(n2b97712333, g, e, l2b94e04bf2, l2b924f74b1)
N(n15e9a83652, g, d, n15e1f5b08f, n15da432acc)
N(n15e1f5b08f, h, d, n15e1f2fc94, n15e1f04899)
N(n15e1f2fc94, i, d, l15e1f2fc43, n15e1f2fbf2)
N(n15e1f2fbf2, i, e, l15e1f2fbd7, l15e1f2fbbc)
N(n15e1f04899, h, e, n15e1ef61f0, l15e1ee7b47)
N(n15e1ef61f0, i, e, l15e1ef61d5, l15e1ef61ba)
N(n15da432acc, f, d, ne8bce32b3, n73d593a9a)
N(ne8bce32b3, h, e, ne8bcd4c0a, ne8bcc6561)
N(ne8bcd4c0a, i, e, le8bcd4bef, le8bcd4bd4)
N(ne8bcc6561, g, e, le893b8e20, le86aab6df)
N(n73d593a9a, g, e, n73ac86359, n738378c18)
N(n73ac86359, h, e, n73ac77cb0, l73ac69607)
N(n73ac77cb0, i, e, l73ac77c95, l73ac77c7a)
N(n738378c18, f, e, l4c8bb3965, l2593ee6b2)

l189bad066d4:X(a,e,i,d,h,c,g,b,f);R
l189bad05b70:X(a,d,h,c,g,b,f);X(e,i);R
l189bad05897:X(a,d,h,c,g,b,e,i,f);R
l189bad06e1b:X(a,d,h,c,f);X(b,e,i,g);R
l189bad06daf:X(a,d,g,b,e,i,h,c,f);R
l189bad06d94:X(a,d,g,b,e,h,c,f);R
l189ba6f1d3a:X(a,c,g,b,f);X(d,h);X(e,i);R
l189ba6f1a61:X(a,c,g,b,e,i,f);X(d,h);R
l189ba6f1ecf:X(a,c,f);X(b,e,i,g);X(d,h);R
l189ba6f1e63:X(a,c,f);X(b,e,i,h,d,g);R
l189ba6f1e48:X(a,c,f);X(b,e,h,d,g);R
l189ba56cbef:X(a,c,g,b,d,h,e,i,f);R
l189ba56cafc:X(a,c,f);X(b,d,h,e,i,g);R
l189ba56cc76:X(a,c,f);X(b,d,g);X(e,i,h);R
l189ba56cc5b:X(a,c,f);X(b,d,g);X(e,h);R
l188eb2cf93d:X(a,b,f);X(c,g);X(d,h);X(e,i);R
l188eb2cf571:X(a,b,e,i,f);X(c,g);X(d,h);R
l188eb2cf47e:X(a,b,e,i,g,c,f);X(d,h);R
l188a5cdf375:X(a,b,d,h,e,i,f);X(c,g);R
l188a5cdf282:X(a,b,d,h,e,i,g,c,f);R
l18860873f9a:X(a,b,c,g,d,h,e,i,f);R
l18860873ea7:X(a,b,c,f);X(d,h,e,i,g);R
l188a5e647cf:X(a,b,e,i,h,d,g,c,f);R
l188a5cdf3fc:X(a,b,d,g,c,f);X(e,i,h);R
l18860b7e7c7:X(a,b,c,f);X(d,g);X(e,i,h);R
l188a5e647b4:X(a,b,e,h,d,g,c,f);R
l188a5cdf3e1:X(a,b,d,g,c,f);X(e,h);R
l18860b7e7ac:X(a,b,c,f);X(d,g);X(e,h);R
l18975c7e798:X(a,c,e,i,g,b,d,h,f);R
l18975c7e747:X(a,c,e,i,h,f);X(b,d,g);R
l18975c533ee:X(a,c,e,i,h,g,b,d,f);R
l188a5f3cc07:X(a,b,d,h,f);X(c,e,i,g);R
l188a5f3cbb6:X(a,b,d,g,c,e,i,h,f);R
l188a5f1185d:X(a,b,d,f);X(c,e,i,h,g);R
l189e93dbe05:X(a,b,c,e,i,g,d,h,f);R
l189e93dbdb4:X(a,b,c,e,i,h,f);X(d,g);R
l189e93b0a5b:X(a,b,c,e,i,h,g,d,f);R
l189d2262cbc:X(a,b,c,d,h,f);X(e,i,g);R
l189d2262c6b:X(a,b,c,d,g,e,i,h,f);R
l189ca70f34f:X(a,b,c,d,f);X(e,i,h,g);R
l189c2be6d8c:X(a,b,c,d,e,i,h,g,f);R
l18975c7e7ce:X(a,c,e,h,f);X(b,d,g);R
l18975c44d2a:X(a,c,e,h,g,b,d,f);R
l18975c36681:X(a,c,e,g,b,d,f);R
l188a5f3cc3d:X(a,b,d,g,c,e,h,f);R
l188a5f03199:X(a,b,d,f);X(c,e,h,g);R
l188a5ef4af0:X(a,b,d,f);X(c,e,g);R
l189e93cd792:X(a,b,c,e,h,f);X(d,g);R
l189e93a2397:X(a,b,c,e,h,g,d,f);R
l189ca72c086:X(a,b,c,d,g,e,h,f);R
l189ca700c8b:X(a,b,c,d,f);X(e,h,g);R
l189c2c2eebe:X(a,b,c,d,e,h,g,f);R
l189e18c1f21:X(a,b,c,e,g,d,f);R
l189ca748dd8:X(a,b,c,d,f);X(e,g);R
l189ee605366:X(a,b,c,d,e,g,f);R
l189ebcf7c25:X(a,b,c,d,e,f);R
l833d1b985e:X(b,f);X(c,g);X(d,h);X(e,i);R
l833d1b9585:X(b,e,i,f);X(c,g);X(d,h);R
l833d1b99f3:X(b,e,i,g,c,f);X(d,h);R
l833d1b9987:X(b,e,i,h,d,g,c,f);R
l833d1b996c:X(b,e,h,d,g,c,f);R
l833d034713:X(b,d,h,e,i,f);X(c,g);R
l833d034620:X(b,d,h,e,i,g,c,f);R
l833d03479a:X(b,d,g,c,f);X(e,i,h);R
l833d03477f:X(b,d,g,c,f);X(e,h);R
l833d291fc0:X(b,d,h,f);X(c,e,i,g);R
l833d291f54:X(b,d,g,c,e,i,h,f);R
l833d291f39:X(b,d,g,c,e,h,f);R
l833d258552:X(b,d,f);X(c,e,i,h,g);R
l833d258537:X(b,d,f);X(c,e,h,g);R
l833d249ec4:X(b,d,f);X(c,e,g);R
l82e0d5a995:X(b,c,g,d,h,e,i,f);R
l82e0d5a8a2:X(b,c,f);X(d,h,e,i,g);R
l82e0d5aa1c:X(b,c,f);X(d,g);X(e,i,h);R
l82e0d5aa01:X(b,c,f);X(d,g);X(e,h);R
l82e0cada9c:X(b,c,e,i,g,d,h,f);R
l82e0cada30:X(b,c,e,i,h,f);X(d,g);R
l82e0cada15:X(b,c,e,h,f);X(d,g);R
l82e0c7402e:X(b,c,e,i,h,g,d,f);R
l82e0c74013:X(b,c,e,h,g,d,f);R
l82e0c659a0:X(b,c,e,g,d,f);R
l82c210fb72:X(b,c,d,h,f);X(e,i,g);R
l82c210fb06:X(b,c,d,g,e,i,h,f);R
l82c210faeb:X(b,c,d,g,e,h,f);R
l82c20d6104:X(b,c,d,f);X(e,i,h,g);R
l82c20d60e9:X(b,c,d,f);X(e,h,g);R
l82c20c7a76:X(b,c,d,f);X(e,g);R
l82ba604337:X(b,c,d,e,i,h,g,f);R
l82ba60431c:X(b,c,d,e,h,g,f);R
l82b7ce8568:X(b,c,d,e,g,f);R
l82b53dae27:X(b,c,d,e,f);R
l2bbde7701f:X(c,g,d,h,e,i,f);R
l2bbde76f2c:X(c,f);X(d,h,e,i,g);R
l2bbde770a6:X(c,f);X(d,g);X(e,i,h);R
l2bbde7708b:X(c,f);X(d,g);X(e,h);R
l2bbddca126:X(c,e,i,g,d,h,f);R
l2bbddca0ba:X(c,e,i,h,f);X(d,g);R
l2bbddca09f:X(c,e,h,f);X(d,g);R
l2bbdd906b8:X(c,e,i,h,g,d,f);R
l2bbdd9069d:X(c,e,h,g,d,f);R
l2bbdd8202a:X(c,e,g,d,f);R
l2b9f22c1fc:X(c,d,h,f);X(e,i,g);R
l2b9f22c190:X(c,d,g,e,i,h,f);R
l2b9f22c175:X(c,d,g,e,h,f);R
l2b9f1f278e:X(c,d,f);X(e,i,h,g);R
l2b9f1f2773:X(c,d,f);X(e,h,g);R
l2b9f1e4100:X(c,d,f);X(e,g);R
l2b977209c1:X(c,d,e,i,h,g,f);R
l2b977209a6:X(c,d,e,h,g,f);R
l2b94e04bf2:X(c,d,e,g,f);R
l2b924f74b1:X(c,d,e,f);R
l15e1f2fc43:X(d,h,f);X(e,i,g);R
l15e1f2fbd7:X(d,g,e,i,h,f);R
l15e1f2fbbc:X(d,g,e,h,f);R
l15e1ef61d5:X(d,f);X(e,i,h,g);R
l15e1ef61ba:X(d,f);X(e,h,g);R
l15e1ee7b47:X(d,f);X(e,g);R
le8bcd4bef:X(d,e,i,h,g,f);R
le8bcd4bd4:X(d,e,h,g,f);R
le893b8e20:X(d,e,g,f);R
le86aab6df:X(d,e,f);R
l73ac77c95:X(e,i,h,g,f);R
l73ac77c7a:X(e,h,g,f);R
l73ac69607:X(e,g,f);R
l4c8bb3965:X(e,f);R
l2593ee6b2:R_SORTED
}
#undef N
#undef DT_UNLIKELY
#undef R
#undef R_SORTED
