#pragma once
// Decision Tree Statistics:
//   Leaves: 120
//   Nodes:  239
//   Max depth: 7
//   Min depth: 6
//   Average path length: 6.93333
//   Path length (sorted input): 7
//   Path length (reverse input): 7
//   Tree fullness: 93.75% (120 / 2^7)

#include "cycle.hh"

// Generated by dtsort-codegen
#ifndef DT_ADAPTIVE
#define DT_ADAPTIVE 1
#endif
#define N(label, row, col, labelTrue, labelFalse) label: if (compare(row, col)) goto labelTrue; else goto labelFalse;
#if DT_ADAPTIVE
#define R return false;
#define R_SORTED return true;
#else
#define R return;
#define R_SORTED return;
#endif

template<typename RandomAccessIterator, typename Compare>
#if defined(__GNUC__) || defined(__clang__)
__attribute__((always_inline))
#endif
#if DT_ADAPTIVE
// Returns true if the input was already sorted and no swaps were performed.
inline bool dtsort5(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
#else
inline void dtsort5(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
#endif
assert(last-first==5);
auto &a = *(first+0);
auto &b = *(first+1);
auto &c = *(first+2);
auto &d = *(first+3);
auto &e = *(first+4);

N(ne6a8, b, a, n99c5, n4ce2)
N(n99c5, d, c, n9974, n9923)
N(n9974, c, a, n7fd3, n6632)
N(n7fd3, e, c, n7fd0, n7fcd)
N(n7fd0, e, d, n7fcf, n7fce)
N(n7fcf, d, b, n7edc, n7de9)
N(n7edc, c, b, l7651, l6dc6)
N(n7de9, e, b, l7de0, l7dd7)
N(n7fce, e, b, n7fc5, n7fbc)
N(n7fc5, c, b, l773a, l6eaf)
N(n7fbc, d, b, l7ec9, l7dd6)
N(n7fcd, c, b, n7742, n6eb7)
N(n7742, e, a, n7727, l770c)
N(n7727, e, b, l771e, l7715)
N(n6eb7, d, b, n6dc4, n6cd1)
N(n6dc4, e, a, l6da9, l6d8e)
N(n6cd1, e, a, l6cb6, l6c9b)
N(n6632, e, a, n6617, n65fc)
N(n6617, e, b, n660e, n6605)
N(n660e, d, b, n651b, n6428)
N(n651b, e, d, l651a, l6519)
N(n6428, d, a, l614f, l5e76)
N(n6605, e, d, n6604, n6603)
N(n6604, d, a, l632b, l6052)
N(n6603, d, b, l6510, l641d)
N(n65fc, d, a, n6323, n604a)
N(n6323, d, b, n6230, n613d)
N(n6230, e, c, l622d, l622a)
N(n613d, e, c, l613a, l6137)
N(n604a, e, c, n6047, l6044)
N(n6047, e, d, l6046, l6045)
N(n9923, c, b, n9098, n880d)
N(n9098, e, b, n908f, n9086)
N(n908f, d, b, n8f9c, n8ea9)
N(n8f9c, e, c, l8f99, n8f96)
N(n8f96, e, d, l8f95, l8f94)
N(n8ea9, d, a, n8bd0, n88f7)
N(n8bd0, e, c, l8bcd, l8bca)
N(n88f7, e, c, l88f4, l88f1)
N(n9086, e, a, n906b, n9050)
N(n906b, e, d, n906a, n9069)
N(n906a, d, a, l8d91, l8ab8)
N(n9069, d, b, l8f76, l8e83)
N(n9050, d, a, n8d77, n8a9e)
N(n8d77, d, b, l8c84, l8b91)
N(n8a9e, e, d, l8a9d, l8a9c)
N(n880d, e, c, n880a, n8807)
N(n880a, c, a, n6e69, n54c8)
N(n6e69, d, a, n6b90, n68b7)
N(n6b90, e, b, l6b87, l6b7e)
N(n68b7, e, b, l68ae, l68a5)
N(n54c8, e, a, n54ad, l5492)
N(n54ad, e, b, l54a4, l549b)
N(n8807, e, d, n8806, n8805)
N(n8806, e, a, n87eb, n87d0)
N(n87eb, d, a, l8512, l8239)
N(n87d0, c, a, l6e2f, l548e)
N(n8805, d, a, n852c, n8253)
N(n852c, e, a, l8511, l84f6)
N(n8253, c, a, l68b2, l4f11)
N(n4ce2, d, c, n4c91, n4c40)
N(n4c91, c, b, n4406, n3b7b)
N(n4406, e, c, n4403, n4400)
N(n4403, e, d, n4402, n4401)
N(n4402, d, a, n4129, n3e50)
N(n4129, c, a, l2788, lde7)
N(n3e50, e, a, l3e35, l3e1a)
N(n4401, e, a, n43e6, n43cb)
N(n43e6, c, a, l2a45, l10a4)
N(n43cb, d, a, l40f2, l3e19)
N(n4400, c, a, n2a5f, n10be)
N(n2a5f, e, a, l2a44, n2a29)
N(n2a29, e, b, l2a20, l2a17)
N(n10be, d, a, nde5, nb0c)
N(nde5, e, b, lddc, ldd3)
N(nb0c, e, b, lb03, lafa)
N(n3b7b, e, b, n3b72, n3b69)
N(n3b72, e, a, n3b57, n3b3c)
N(n3b57, d, a, n387e, n35a5)
N(n387e, e, d, l387d, l387c)
N(n35a5, d, b, l34b2, l33bf)
N(n3b3c, e, d, n3b3b, n3b3a)
N(n3b3b, d, b, l3a48, l3955)
N(n3b3a, d, a, l3861, l3588)
N(n3b69, d, b, n3a76, n3983)
N(n3a76, d, a, n379d, n34c4)
N(n379d, e, c, l379a, l3797)
N(n34c4, e, c, l34c1, l34be)
N(n3983, e, c, n3980, l397d)
N(n3980, e, d, l397f, l397e)
N(n4c40, c, a, n329f, n18fe)
N(n329f, e, a, n3284, n3269)
N(n3284, d, a, n2fab, n2cd2)
N(n2fab, e, c, l2fa8, n2fa5)
N(n2fa5, e, d, l2fa4, l2fa3)
N(n2cd2, d, b, n2bdf, n2aec)
N(n2bdf, e, c, l2bdc, l2bd9)
N(n2aec, e, c, l2ae9, l2ae6)
N(n3269, e, b, n3260, n3257)
N(n3260, e, d, n325f, n325e)
N(n325f, d, b, l316c, l3079)
N(n325e, d, a, l2f85, l2cac)
N(n3257, d, b, n3164, n3071)
N(n3164, d, a, l2e8b, l2bb2)
N(n3071, e, d, l3070, l306f)
N(n18fe, e, c, n18fb, n18f8)
N(n18fb, c, b, n1070, n7e5)
N(n1070, d, b, nf7d, ne8a)
N(nf7d, e, a, lf62, lf47)
N(ne8a, e, a, le6f, le54)
N(n7e5, e, a, l7ca, n7af)
N(n7af, e, b, l7a6, l79d)
N(n18f8, e, d, n18f7, n18f6)
N(n18f7, e, b, n18ee, n18e5)
N(n18ee, d, b, l17fb, l1708)
N(n18e5, c, b, l105a, l7cf)
N(n18f6, d, b, n1803, n1710)
N(n1803, e, b, l17fa, l17f1)
N(n1710, c, b, le85, l5fa)

l7651:X(a,e);X(b,d);R
l6dc6:X(a,e);X(b,c,d);R
l7de0:X(a,e);X(c,d);R
l7dd7:X(a,e,b);X(c,d);R
l773a:X(a,e,b,d);R
l6eaf:X(a,e,b,c,d);R
l7ec9:X(a,e,c,d);R
l7dd6:X(a,e,c,d,b);R
l771e:X(a,e,c,b,d);R
l7715:X(a,e,d);X(b,c);R
l770c:X(a,d);X(b,c);R
l6da9:X(a,e,d);R
l6d8e:X(a,d);R
l6cb6:X(a,e,d,b);R
l6c9b:X(a,d,b);R
l651a:X(a,d,b,c,e);R
l6519:X(a,d);X(b,c,e);R
l614f:X(a,d,c,e);R
l5e76:X(a,c,e);R
l632b:X(a,d,c,e,b);R
l6052:X(a,c,e,b);R
l6510:X(a,d);X(c,e);R
l641d:X(a,d,b);X(c,e);R
l622d:X(a,c,e,d);R
l622a:X(a,c,d);R
l613a:X(a,c,e,d,b);R
l6137:X(a,c,d,b);R
l6046:X(a,b);X(c,e);R
l6045:X(a,b);X(c,e,d);R
l6044:X(a,b);X(c,d);R
l8f99:X(a,e);X(b,d,c);R
l8f95:X(a,e,b,d,c);R
l8f94:X(a,e,c);X(b,d);R
l8bcd:X(a,e);X(b,c);R
l8bca:X(a,e,b,c);R
l88f4:X(a,d,e);X(b,c);R
l88f1:X(a,d,e,b,c);R
l8d91:X(a,e,c);R
l8ab8:X(a,d,e,c);R
l8f76:X(a,e,d,b,c);R
l8e83:X(a,e,d,c);R
l8c84:X(a,d,b,c);R
l8b91:X(a,d,c);R
l8a9d:X(a,c);X(d,e);R
l8a9c:X(a,c);R
l6b87:X(a,e);R
l6b7e:X(a,e,b);R
l68ae:X(a,d,e);R
l68a5:X(a,d,e,b);R
l54a4:X(a,c,d,e);R
l549b:X(a,c,d,e,b);R
l5492:X(a,b);X(c,d,e);R
l8512:X(a,e,c,b);R
l8239:X(a,d,e,c,b);R
l6e2f:X(a,c,b);X(d,e);R
l548e:X(a,b);X(d,e);R
l8511:X(a,e,d,c,b);R
l84f6:X(a,d,c,b);R
l68b2:X(a,c,b);R
l4f11:X(a,b);R
l2788:X(a,d,b,e);R
lde7:X(a,c,d,b,e);R
l3e35:X(a,b,e);X(c,d);R
l3e1a:X(b,e);X(c,d);R
l2a45:X(a,d);X(b,e);R
l10a4:X(a,c,d);X(b,e);R
l40f2:X(a,b,e,c,d);R
l3e19:X(b,e,c,d);R
l2a44:X(a,d);X(b,e,c);R
l2a20:X(a,c,b,e,d);R
l2a17:X(a,c,b,d);R
lddc:X(a,b,e,d);R
ldd3:X(a,b,d);R
lb03:X(b,e,d);R
lafa:X(b,d);R
l387d:X(a,c,e);X(b,d);R
l387c:X(a,c,e,b,d);R
l34b2:X(a,b,d,c,e);R
l33bf:X(a,b,c,e);R
l3a48:X(b,d,c,e);R
l3955:X(b,c,e);R
l3861:X(a,b,d);X(c,e);R
l3588:X(b,d);X(c,e);R
l379a:X(a,b,c,e,d);R
l3797:X(a,b,c,d);R
l34c1:X(b,c,e,d);R
l34be:X(b,c,d);R
l397f:X(c,e);R
l397e:X(c,e,d);R
l397d:X(c,d);R
l2fa8:X(a,d,c,b,e);R
l2fa4:X(a,d,c);X(b,e);R
l2fa3:X(a,d,b,e,c);R
l2bdc:X(a,c,b,e);R
l2bd9:X(a,c);X(b,e);R
l2ae9:X(a,c,b,d,e);R
l2ae6:X(a,c);X(b,d,e);R
l316c:X(a,b,e,c);R
l3079:X(a,b,d,e,c);R
l2f85:X(a,c);X(b,e,d);R
l2cac:X(a,b,e,d,c);R
l2e8b:X(a,c);X(b,d);R
l2bb2:X(a,b,d,c);R
l3070:X(a,b,c);X(d,e);R
l306f:X(a,b,c);R
lf62:X(a,b,e);R
lf47:X(b,e);R
le6f:X(a,b,d,e);R
le54:X(b,d,e);R
l7ca:X(a,b,c,d,e);R
l7a6:X(b,c,d,e);R
l79d:X(c,d,e);R
l17fb:X(b,e,c);R
l1708:X(b,d,e,c);R
l105a:X(b,c);X(d,e);R
l7cf:X(d,e);R
l17fa:X(b,e,d,c);R
l17f1:X(b,d,c);R
le85:X(b,c);R
l5fa:R_SORTED
}
#undef N
#undef R
#undef R_SORTED
