#pragma once
// Stats: {"leaves":2,"nodes":3,"maxDepth":1,"minDepth":1,"avgPath":1,"sortedPath":1,"reversePath":1,"fullness":100}

#include "dtsort_common.hh"

// Generated by dtsort-codegen
#define N(label, row, col, labelTrue, labelFalse) label: if (compare(row, col)) goto labelTrue; else goto labelFalse;
#define R DT_RETURN
#define R_SORTED DT_RETURN_SORTED

template<typename RandomAccessIterator, typename Compare>
DT_ALWAYS_INLINE
inline DT_RETURN_TYPE dtsort2(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
assert(last-first==2);
auto &a = *(first+0);
auto &b = *(first+1);

N(n_,b,a,l1,l0)

l1:X(a,b);R
l0:R_SORTED
}
#undef N
#undef R
#undef R_SORTED
