#pragma once

// Stats: {"leaves":24,"nodes":47,"maxDepth":5,"minDepth":4,"avgPath":4.66667,"sortedPath":4,"reversePath":4,"fullness":75}

#include "dtsort_common.hh"

// Generated by dtsort-codegen
#define N(label, row, col, labelTrue, labelFalse) label: if (compare(row, col)) goto labelTrue; else goto labelFalse;
#define R DT_RETURN
#define R_SORTED DT_RETURN_SORTED

template<typename RandomAccessIterator, typename Compare>
DT_ALWAYS_INLINE
inline DT_RETURN_TYPE dtsort4(const RandomAccessIterator& first, [[maybe_unused]] const RandomAccessIterator& last, const Compare& compare) {
assert(last-first==4);
auto &a = *(first+0);
auto &b = *(first+1);
auto &c = *(first+2);
auto &d = *(first+3);

N(n______,b,a,n1_____,n0_____)
N(n1_____,d,c,n1____1,n1____0)
N(n1____1,c,a,n11___1,n10___1)
N(n11___1,c,b,l111__1,n110__1)
N(n110__1,d,b,l110_11,l110_01)
N(n10___1,d,a,n10_1_1,l10_0_1)
N(n10_1_1,d,b,l10_111,l10_101)
N(n1____0,c,b,n1_1__0,n1_0__0)
N(n1_1__0,d,a,n1_11_0,l1_10_0)
N(n1_11_0,d,b,l1_1110,l1_1100)
N(n1_0__0,c,a,n110__0,l100__0)
N(n110__0,d,a,l1101_0,l1100_0)
N(n0_____,d,c,n0____1,n0____0)
N(n0____1,c,b,n0_1__1,n0_0__1)
N(n0_1__1,c,a,l011__1,n001__1)
N(n001__1,d,a,l0011_1,l0010_1)
N(n0_0__1,d,a,l0_01_1,n0_00_1)
N(n0_00_1,d,b,l0_0011,l0_0001)
N(n0____0,c,a,n01___0,n00___0)
N(n01___0,d,a,l01_1_0,n01_0_0)
N(n01_0_0,d,b,l01_010,l01_000)
N(n00___0,c,b,n001__0,l000__0)
N(n001__0,d,b,l001_10,l001_00)

l111__1:X(a,d);X(b,c);R
l110_11:X(a,d);R
l110_01:X(a,d,b);R
l10_111:X(a,c,d);R
l10_101:X(a,c,d,b);R
l10_0_1:X(a,b);X(c,d);R
l1_1110:X(a,d,b,c);R
l1_1100:X(a,d,c);R
l1_10_0:X(a,c);R
l1101_0:X(a,d,c,b);R
l1100_0:X(a,c,b);R
l100__0:X(a,b);R
l011__1:X(a,c,b,d);R
l0011_1:X(a,b,d);R
l0010_1:X(b,d);R
l0_01_1:X(a,b,c,d);R
l0_0011:X(b,c,d);R
l0_0001:X(c,d);R
l01_1_0:X(a,c);X(b,d);R
l01_010:X(a,b,d,c);R
l01_000:X(a,b,c);R
l001_10:X(b,d,c);R
l001_00:X(b,c);R
l000__0:R_SORTED
}
#undef N
#undef R
#undef R_SORTED
