#pragma once
// Stats: {"leaves":6,"nodes":11,"maxDepth":3,"minDepth":2,"avgPath":2.66667,"sortedPath":3,"reversePath":3,"fullness":75}

#include "dtsort_common.hh"

// Generated by dtsort-codegen
#define N(label, row, col, labelTrue, labelFalse) label: if (compare(row, col)) goto labelTrue; else goto labelFalse;
#define R DT_RETURN
#define R_SORTED DT_RETURN_SORTED

template<typename RandomAccessIterator, typename Compare>
DT_ALWAYS_INLINE
inline DT_RETURN_TYPE dtsort3(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
assert(last-first==3);
auto &a = *(first+0);
auto &b = *(first+1);
auto &c = *(first+2);

N(n___,b,a,n1__,n0__)
N(n1__,c,a,n11_,l10_)
N(n11_,c,b,l111,l110)
N(n0__,c,a,l01_,n00_)
N(n00_,c,b,l001,l000)

l111:X(a,c);R
l110:X(a,c,b);R
l10_:X(a,b);R
l01_:X(a,b,c);R
l001:X(b,c);R
l000:R_SORTED
}
#undef N
#undef R
#undef R_SORTED
