#pragma once
// Decision Tree Statistics:
//   Leaves: 6
//   Nodes:  11
//   Max depth: 3
//   Min depth: 2
//   Average path length: 2.66667
//   Path length (sorted input): 3
//   Path length (reverse input): 3
//   Tree fullness: 75% (6 / 2^3)

#include "cycle.hh"

// Generated by dtsort-codegen
#ifndef DT_ADAPTIVE
#define DT_ADAPTIVE 1
#endif
#define N(label, row, col, labelTrue, labelFalse) label: if (compare(row, col)) goto labelTrue; else goto labelFalse;
#if DT_ADAPTIVE
#define R return false;
#define R_SORTED return true;
#else
#define R return;
#define R_SORTED return;
#endif

template<typename RandomAccessIterator, typename Compare>
#if defined(__GNUC__) || defined(__clang__)
__attribute__((always_inline))
#endif
#if DT_ADAPTIVE
// Returns true if the input was already sorted and no swaps were performed.
inline bool dtsort3(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
#else
inline void dtsort3(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
#endif
assert(last-first==3);
auto &a = *(first+0);
auto &b = *(first+1);
auto &c = *(first+2);

N(n___, b, a, n1__, n0__)
N(n1__, c, a, n11_, l10_)
N(n11_, c, b, l111, l110)
N(n0__, c, a, l01_, n00_)
N(n00_, c, b, l001, l000)

l111:X(a,c);R
l110:X(a,c,b);R
l10_:X(a,b);R
l01_:X(a,b,c);R
l001:X(b,c);R
l000:R_SORTED
}
#undef N
#undef R
#undef R_SORTED
