#pragma once

// Stats: {"leaves":21,"nodes":41,"maxDepth":5,"minDepth":4,"avgPath":4.47619,"sortedPath":4,"reversePath":4,"fullness":65.625}

#include "dtsort_common.hh"
#include "dtsort2_full.hh"
#include "dtsort5_full.hh"

// Generated by dtsort-codegen
#define N(label, row, col, labelTrue, labelFalse) label: if (compare(row, col)) goto labelTrue; else goto labelFalse;
#define R DT_RETURN
#define R_SORTED DT_RETURN_SORTED

template<typename RandomAccessIterator, typename Compare>
DT_ALWAYS_INLINE
inline DT_RETURN_TYPE dtsort7gs52(const RandomAccessIterator& first, [[maybe_unused]] const RandomAccessIterator& last, const Compare& compare) {
assert(last-first==7);
auto &a = *(first+0);
auto &b = *(first+1);
auto &c = *(first+2);
auto &d = *(first+3);
auto &e = *(first+4);
auto &f = *(first+5);
auto &g = *(first+6);

#if DT_ADAPTIVE
bool s1 = dtsort5(first, first+5, compare);
bool s2 = dtsort2(first+5, first+7, compare);
if (DT_UNLIKELY(s1 && s2 && !compare(*(first+5), *(first+4)))) return true;
#else
dtsort5(first, first+5, compare);
dtsort2(first+5, first+7, compare);
#endif

N(n2b3f8,f,b,n26715,n21a32)
N(n26715,f,a,n1806c,n99c3)
N(n1806c,g,c,n18051,n18036)
N(n18051,g,a,l17f5e,n17e6b)
N(n17e6b,g,b,l17e1a,l17dc9)
N(n18036,g,d,l1802d,n18024)
N(n18024,g,e,l18021,l1801e)
N(n99c3,g,c,n99a8,n998d)
N(n99a8,g,b,l9957,l9906)
N(n998d,g,d,l9984,n997b)
N(n997b,g,e,l9978,l9975)
N(n21a32,f,c,n20091,n1e6f0)
N(n20091,g,d,n20088,n2007f)
N(n20088,g,c,l2006d,l20052)
N(n2007f,g,e,l2007c,l20079)
N(n1e6f0,f,d,n1de65,n1d5da)
N(n1de65,g,d,l1de5c,n1de53)
N(n1de53,g,e,l1de50,l1de4d)
N(n1d5da,f,e,n1d301,l1d028)
N(n1d301,g,e,l1d2fe,l1d2fb)

l17f5e:X(a,c,e,g,b,d,f);R
l17e1a:X(a,b,d,f);X(c,e,g);R
l17dc9:X(a,b,c,e,g,d,f);R
l1802d:X(a,b,c,d,f);X(e,g);R
l18021:X(a,b,c,d,e,g,f);R
l1801e:X(a,b,c,d,e,f);R
l9957:X(b,d,f);X(c,e,g);R
l9906:X(b,c,e,g,d,f);R
l9984:X(b,c,d,f);X(e,g);R
l9978:X(b,c,d,e,g,f);R
l9975:X(b,c,d,e,f);R
l2006d:X(c,e,g,d,f);R
l20052:X(c,d,f);X(e,g);R
l2007c:X(c,d,e,g,f);R
l20079:X(c,d,e,f);R
l1de5c:X(d,f);X(e,g);R
l1de50:X(d,e,g,f);R
l1de4d:X(d,e,f);R
l1d2fe:X(e,g,f);R
l1d2fb:X(e,f);R
l1d028:R_SORTED
}
#undef N
#undef R
#undef R_SORTED
