#pragma once
// Decision Tree Statistics:
//   Leaves: 2
//   Nodes:  3
//   Max depth: 1
//   Min depth: 1
//   Average path length: 1
//   Path length (sorted input): 1
//   Path length (reverse input): 1
//   Tree fullness: 100% (2 / 2^1)

#include "cycle.hh"

// Generated by dtsort-codegen
#ifndef DT_ADAPTIVE
#define DT_ADAPTIVE 1
#endif
#define N(label, row, col, labelTrue, labelFalse) label: if (compare(row, col)) goto labelTrue; else goto labelFalse;
#if DT_ADAPTIVE
#define R return false;
#define R_SORTED return true;
#else
#define R return;
#define R_SORTED return;
#endif

template<typename RandomAccessIterator, typename Compare>
#if defined(__GNUC__) || defined(__clang__)
__attribute__((always_inline))
#endif
#if DT_ADAPTIVE
// Returns true if the input was already sorted and no swaps were performed.
inline bool dtsort2(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
#else
inline void dtsort2(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
#endif
assert(last-first==2);
auto &a = *(first+0);
auto &b = *(first+1);

N(n_, b, a, l1, l0)

l1:X(a,b);R
l0:R_SORTED
}
#undef N
#undef R
#undef R_SORTED
