#pragma once
// Stats: {"leaves":15,"nodes":29,"maxDepth":5,"minDepth":3,"avgPath":4,"sortedPath":3,"reversePath":4,"fullness":46.875}

#include "dtsort_common.hh"
#include "dtsort2_full.hh"
#include "dtsort4_full.hh"

// Generated by dtsort-codegen
#define N(label, row, col, labelTrue, labelFalse) label: if (compare(row, col)) goto labelTrue; else goto labelFalse;
#define R DT_RETURN
#define R_SORTED DT_RETURN_SORTED

template<typename RandomAccessIterator, typename Compare>
DT_ALWAYS_INLINE
inline DT_RETURN_TYPE dtsort6gs42(const RandomAccessIterator& first, const RandomAccessIterator& last, const Compare& compare) {
assert(last-first==6);
auto &a = *(first+0);
auto &b = *(first+1);
auto &c = *(first+2);
auto &d = *(first+3);
auto &e = *(first+4);
auto &f = *(first+5);

#if DT_ADAPTIVE
bool s1 = dtsort4(first, first+4, compare);
bool s2 = dtsort2(first+4, first+6, compare);
if (DT_UNLIKELY(s1 && s2 && !compare(*(first+4), *(first+3)))) return true;
#else
dtsort4(first, first+4, compare);
dtsort2(first+4, first+6, compare);
#endif

N(n4ce0,e,b,n4455,n3bca)
N(n4455,e,a,n2ab4,n1113)
N(n2ab4,f,b,n2a99,n2a7e)
N(n2a99,f,a,l2a48,l29f7)
N(n2a7e,f,c,l2a75,n2a6c)
N(n2a6c,f,d,l2a69,l2a66)
N(n1113,f,c,n110a,n1101)
N(n110a,f,b,l10ef,l10d4)
N(n1101,f,d,l10fe,l10fb)
N(n3bca,e,c,n38f1,n3618)
N(n38f1,f,c,l38e8,n38df)
N(n38df,f,d,l38dc,l38d9)
N(n3618,e,d,n3525,l3432)
N(n3525,f,d,l3522,l351f)

l2a48:X(a,c,e);X(b,d,f);R
l29f7:X(a,b,d,f,c,e);R
l2a75:X(a,b,c,e);X(d,f);R
l2a69:X(a,b,c,d,f,e);R
l2a66:X(a,b,c,d,e);R
l10ef:X(b,d,f,c,e);R
l10d4:X(b,c,e);X(d,f);R
l10fe:X(b,c,d,f,e);R
l10fb:X(b,c,d,e);R
l38e8:X(c,e);X(d,f);R
l38dc:X(c,d,f,e);R
l38d9:X(c,d,e);R
l3522:X(d,f,e);R
l351f:X(d,e);R
l3432:R_SORTED
}
#undef N
#undef R
#undef R_SORTED
